package knowledge

import "ai-agent/internal/domain"

var staticDocuments = [...]domain.Document{
	{
		ID:       "identity-basic-pt",
		Category: "identity",
		Language: "pt",
		Content:  "João Paulo Dias Ventura é um Engenheiro de Software Full Stack de São Paulo.",
	},
	{
		ID:       "identity-basic-en",
		Category: "identity",
		Language: "en",
		Content:  "João Paulo Dias Ventura is a Full Stack Software Engineer from São Paulo.",
	},
	{
		ID:       "identity-professional-summary-pt",
		Category: "identity",
		Language: "pt",
		Content:  "João Paulo desenvolve sistemas usados em processos importantes para empresas, com foco em automação, sistemas financeiros, dados e confiabilidade.",
	},
	{
		ID:       "identity-professional-summary-en",
		Category: "identity",
		Language: "en",
		Content:  "João Paulo builds systems used in important business processes, focusing on automation, financial systems, data, and reliability.",
	},
	{
		ID:       "profile-focus-pt",
		Category: "profile",
		Language: "pt",
		Content:  "João Paulo atua na evolução de sistemas em produção, automatiza processos críticos e integra aplicações com serviços em nuvem.",
	},
	{
		ID:       "profile-focus-en",
		Category: "profile",
		Language: "en",
		Content:  "João Paulo works on the evolution of production systems, automates critical processes, and integrates applications with cloud services.",
	},
	{
		ID:       "profile-delivery-style-pt",
		Category: "profile",
		Language: "pt",
		Content:  "João Paulo conecta backend, frontend, dados e infraestrutura para entregar soluções completas, não apenas partes isoladas.",
	},
	{
		ID:       "profile-delivery-style-en",
		Category: "profile",
		Language: "en",
		Content:  "João Paulo connects backend, frontend, data, and infrastructure work to deliver complete solutions, not only isolated parts.",
	},
	{
		ID:       "profile-reliability-pt",
		Category: "profile",
		Language: "pt",
		Content:  "João Paulo prioriza consistência, escalabilidade e confiabilidade, especialmente em sistemas financeiros e fluxos assíncronos.",
	},
	{
		ID:       "profile-reliability-en",
		Category: "profile",
		Language: "en",
		Content:  "João Paulo prioritizes consistency, scalability, and reliability, especially in financial systems and asynchronous flows.",
	},
	{
		ID:       "profile-autonomy-pt",
		Category: "profile",
		Language: "pt",
		Content:  "João Paulo trabalha em equipes enxutas e ambientes de alta autonomia, assumindo responsabilidades em produto, dados e infraestrutura.",
	},
	{
		ID:       "profile-autonomy-en",
		Category: "profile",
		Language: "en",
		Content:  "João Paulo works in lean teams and high-autonomy environments, taking responsibility across product, data, and infrastructure.",
	},
	{
		ID:       "profile-language-pt",
		Category: "profile",
		Language: "pt",
		Content:  "João Paulo fala português fluentemente e possui inglês avançado.",
	},
	{
		ID:       "profile-language-en",
		Category: "profile",
		Language: "en",
		Content:  "João Paulo speaks Portuguese fluently and has advanced English skills.",
	},
	{
		ID:       "technology-frontend-pt",
		Category: "technology",
		Language: "pt",
		Content:  "João Paulo cria aplicações web com Angular, React e Next.js para entregar interfaces úteis, rápidas e organizadas para usuários e equipes.",
	},
	{
		ID:       "technology-frontend-en",
		Category: "technology",
		Language: "en",
		Content:  "João Paulo builds web applications with Angular, React, and Next.js to deliver useful, fast, and organized interfaces for users and teams.",
	},
	{
		ID:       "technology-backend-pt",
		Category: "technology",
		Language: "pt",
		Content:  "João Paulo usa Java, Spring Boot, Go, Node.js e NestJS para criar APIs, serviços internos, automações e sistemas que processam operações importantes.",
	},
	{
		ID:       "technology-backend-en",
		Category: "technology",
		Language: "en",
		Content:  "João Paulo uses Java, Spring Boot, Go, Node.js, and NestJS to build APIs, internal services, automations, and systems that process important operations.",
	},
	{
		ID:       "technology-databases-pt",
		Category: "technology",
		Language: "pt",
		Content:  "João Paulo trabalha com PostgreSQL, MongoDB e Redis para armazenar dados, consultar informações e apoiar sistemas que precisam de respostas consistentes.",
	},
	{
		ID:       "technology-databases-en",
		Category: "technology",
		Language: "en",
		Content:  "João Paulo works with PostgreSQL, MongoDB, and Redis to store data, query information, and support systems that need consistent responses.",
	},
	{
		ID:       "technology-messaging-pt",
		Category: "technology",
		Language: "pt",
		Content:  "João Paulo utiliza RabbitMQ, Kafka e Amazon SQS para distribuir tarefas, processar operações em segundo plano e evitar que atividades demoradas bloqueiem o usuário.",
	},
	{
		ID:       "technology-messaging-en",
		Category: "technology",
		Language: "en",
		Content:  "João Paulo uses RabbitMQ, Kafka, and Amazon SQS to distribute tasks, process background operations, and prevent slow activities from blocking users.",
	},
	{
		ID:       "technology-cloud-devops-pt",
		Category: "technology",
		Language: "pt",
		Content:  "João Paulo usa AWS, Docker, Terraform e Kubernetes para empacotar aplicações, organizar infraestrutura e executar serviços em ambientes distribuídos.",
	},
	{
		ID:       "technology-cloud-devops-en",
		Category: "technology",
		Language: "en",
		Content:  "João Paulo uses AWS, Docker, Terraform, and Kubernetes to package applications, organize infrastructure, and run services in distributed environments.",
	},
	{
		ID:       "career-current-job-pt",
		Category: "career",
		Language: "pt",
		Content:  "João Paulo trabalha como Desenvolvedor Pleno na uFind Tecnologia desde junho de 2025; a empresa era anteriormente chamada Representa Online.",
	},
	{
		ID:       "career-current-job-en",
		Category: "career",
		Language: "en",
		Content:  "João Paulo has worked as a Mid-Level Developer at uFind Tecnologia since June 2025; the company was previously called Representa Online.",
	},
	{
		ID:       "career-current-responsibilities-pt",
		Category: "career",
		Language: "pt",
		Content:  "Na uFind Tecnologia, João Paulo evolui sistemas financeiros, pipelines de dados e arquitetura cloud em uma equipe enxuta e com alta autonomia.",
	},
	{
		ID:       "career-current-responsibilities-en",
		Category: "career",
		Language: "en",
		Content:  "At uFind Tecnologia, João Paulo evolves financial systems, data pipelines, and cloud architecture in a lean team with high autonomy.",
	},
	{
		ID:       "career-current-problem-pt",
		Category: "career",
		Language: "pt",
		Content:  "Antes da automação criada por João Paulo, processos de faturamento de uma corretora parceira dependiam de operações manuais demoradas e repetitivas.",
	},
	{
		ID:       "career-current-problem-en",
		Category: "career",
		Language: "en",
		Content:  "Before the automation created by João Paulo, billing processes for a partner brokerage depended on slow and repetitive manual operations.",
	},
	{
		ID:       "career-current-automation-pt",
		Category: "impact",
		Language: "pt",
		Content:  "João Paulo automatizou o faturamento de uma corretora parceira, reduzindo atividades repetitivas e melhorando o acompanhamento das etapas do processo.",
	},
	{
		ID:       "career-current-automation-en",
		Category: "impact",
		Language: "en",
		Content:  "João Paulo automated billing for a partner brokerage, reducing repetitive work and improving the tracking of each step in the process.",
	},
	{
		ID:       "career-current-impact-pt",
		Category: "impact",
		Language: "pt",
		Content:  "A automação desenvolvida por João Paulo processa movimentações mensais superiores a R$ 1.000.000,00.",
	},
	{
		ID:       "career-current-impact-en",
		Category: "impact",
		Language: "en",
		Content:  "The automation developed by João Paulo processes monthly financial movements above R$ 1,000,000.00.",
	},
	{
		ID:       "career-current-time-reduction-pt",
		Category: "impact",
		Language: "pt",
		Content:  "João Paulo reduziu operações manuais de faturamento que levavam dias para poucos minutos.",
	},
	{
		ID:       "career-current-time-reduction-en",
		Category: "impact",
		Language: "en",
		Content:  "João Paulo reduced manual billing operations from days to a few minutes.",
	},
	{
		ID:       "career-current-file-processing-pt",
		Category: "career",
		Language: "pt",
		Content:  "João Paulo desenhou pipelines com Node.js Streams e Strategy Pattern para processar diferentes formatos de arquivos financeiros, aplicar validações e evitar duplicação de regras.",
	},
	{
		ID:       "career-current-file-processing-en",
		Category: "career",
		Language: "en",
		Content:  "João Paulo designed pipelines with Node.js Streams and the Strategy Pattern to process different financial file formats, apply validations, and avoid duplicated rules.",
	},
	{
		ID:       "career-current-validation-pt",
		Category: "impact",
		Language: "pt",
		Content:  "As validações criadas por João Paulo ajudaram a tratar múltiplos layouts financeiros com mais consistência e menor risco de regras duplicadas.",
	},
	{
		ID:       "career-current-validation-en",
		Category: "impact",
		Language: "en",
		Content:  "The validations created by João Paulo helped handle multiple financial layouts with more consistency and less risk of duplicated rules.",
	},
	{
		ID:       "career-current-aws-pt",
		Category: "career",
		Language: "pt",
		Content:  "Na uFind Tecnologia, João Paulo contribui constantemente em infraestrutura AWS usando ECS, S3 e IAM.",
	},
	{
		ID:       "career-current-aws-en",
		Category: "career",
		Language: "en",
		Content:  "At uFind Tecnologia, João Paulo contributes regularly to AWS infrastructure using ECS, S3, and IAM.",
	},
	{
		ID:       "career-junior-job-pt",
		Category: "career",
		Language: "pt",
		Content:  "João Paulo trabalhou como Desenvolvedor Júnior na Representa Online entre setembro de 2024 e maio de 2025.",
	},
	{
		ID:       "career-junior-job-en",
		Category: "career",
		Language: "en",
		Content:  "João Paulo worked as a Junior Developer at Representa Online between September 2024 and May 2025.",
	},
	{
		ID:       "career-junior-data-pipelines-pt",
		Category: "impact",
		Language: "pt",
		Content:  "Na Representa Online, João Paulo desenvolveu pipelines para ingestão e processamento de mídia televisiva, preparando mais de 16 GB de dados para consumo por modelos de inteligência artificial.",
	},
	{
		ID:       "career-junior-data-pipelines-en",
		Category: "impact",
		Language: "en",
		Content:  "At Representa Online, João Paulo developed pipelines for television media ingestion and processing, preparing more than 16 GB of data for use by artificial intelligence models.",
	},
	{
		ID:       "career-junior-realtime-pt",
		Category: "career",
		Language: "pt",
		Content:  "João Paulo desenhou a comunicação em tempo real entre um agente de IA e um chat próprio, usando eventos WebSocket para acompanhar a conversa enquanto ela acontecia.",
	},
	{
		ID:       "career-junior-realtime-en",
		Category: "career",
		Language: "en",
		Content:  "João Paulo designed real-time communication between an AI agent and a custom chat, using WebSocket events to follow the conversation as it happened.",
	},
	{
		ID:       "career-junior-message-persistence-pt",
		Category: "impact",
		Language: "pt",
		Content:  "João Paulo garantiu a persistência de cada mensagem no MongoDB, melhorando a continuidade e a rastreabilidade das conversas com o agente de IA.",
	},
	{
		ID:       "career-junior-message-persistence-en",
		Category: "impact",
		Language: "en",
		Content:  "João Paulo ensured every message was persisted in MongoDB, improving continuity and traceability in conversations with the AI agent.",
	},
	{
		ID:       "career-intern-job-pt",
		Category: "career",
		Language: "pt",
		Content:  "João Paulo foi Estagiário em Desenvolvimento de Sistemas na Representa Online entre junho de 2024 e agosto de 2024.",
	},
	{
		ID:       "career-intern-job-en",
		Category: "career",
		Language: "en",
		Content:  "João Paulo was a Systems Development Intern at Representa Online between June 2024 and August 2024.",
	},
	{
		ID:       "career-intern-catalog-pt",
		Category: "career",
		Language: "pt",
		Content:  "Como estagiário, João Paulo desenvolveu funcionalidades para um catálogo digital com foco em performance, escalabilidade e experiência do usuário.",
	},
	{
		ID:       "career-intern-catalog-en",
		Category: "career",
		Language: "en",
		Content:  "As an intern, João Paulo developed features for a digital catalog with focus on performance, scalability, and user experience.",
	},
	{
		ID:       "career-intern-search-pt",
		Category: "impact",
		Language: "pt",
		Content:  "João Paulo implementou busca geoespacial com ordenação por proximidade, usando a fórmula de Haversine para ordenar resultados pela distância do usuário.",
	},
	{
		ID:       "career-intern-search-en",
		Category: "impact",
		Language: "en",
		Content:  "João Paulo implemented geospatial search ordered by proximity, using the Haversine formula to sort results by distance from the user.",
	},
	{
		ID:       "career-intern-auth-performance-pt",
		Category: "career",
		Language: "pt",
		Content:  "No estágio, João Paulo participou de autenticação JWT e OAuth2 e de páginas SSR e SSG com otimizações de TTFB e LCP, métricas ligadas ao carregamento percebido pelo usuário.",
	},
	{
		ID:       "career-intern-auth-performance-en",
		Category: "career",
		Language: "en",
		Content:  "During the internship, João Paulo participated in JWT and OAuth2 authentication and SSR and SSG pages with TTFB and LCP optimizations, metrics related to perceived page loading.",
	},
	{
		ID:       "education-fiap-pt",
		Category: "education",
		Language: "pt",
		Content:  "João Paulo tem formação prevista em Inteligência Artificial pela FIAP entre agosto de 2026 e junho de 2028.",
	},
	{
		ID:       "education-fiap-en",
		Category: "education",
		Language: "en",
		Content:  "João Paulo has Artificial Intelligence studies planned at FIAP between August 2026 and June 2028.",
	},
	{
		ID:       "education-etec-pt",
		Category: "education",
		Language: "pt",
		Content:  "João Paulo concluiu Desenvolvimento de Sistemas na Etec de Guarulhos, com formação entre fevereiro de 2023 e dezembro de 2025.",
	},
	{
		ID:       "education-etec-en",
		Category: "education",
		Language: "en",
		Content:  "João Paulo completed Systems Development at Etec de Guarulhos, with education from February 2023 to December 2025.",
	},
	{
		ID:       "certificate-aws-pt",
		Category: "certificate",
		Language: "pt",
		Content:  "A certificação AWS de João Paulo demonstra estudo sobre implantação de microsserviços no Amazon EKS e modelagem de arquiteturas orientadas a eventos.",
	},
	{
		ID:       "certificate-aws-en",
		Category: "certificate",
		Language: "en",
		Content:  "João Paulo's AWS certification demonstrates study of microservice deployment on Amazon EKS and modeling event-driven architectures.",
	},
	{
		ID:       "certificate-mongodb-pt",
		Category: "certificate",
		Language: "pt",
		Content:  "A certificação MongoDB de João Paulo demonstra conhecimento aplicado ao setor de serviços financeiros.",
	},
	{
		ID:       "certificate-mongodb-en",
		Category: "certificate",
		Language: "en",
		Content:  "João Paulo's MongoDB certification demonstrates knowledge applied to the financial services sector.",
	},
	{
		ID:       "certificate-edb-pt",
		Category: "certificate",
		Language: "pt",
		Content:  "A certificação EDB de João Paulo demonstra estudo sobre PostgreSQL distribuído.",
	},
	{
		ID:       "certificate-edb-en",
		Category: "certificate",
		Language: "en",
		Content:  "João Paulo's EDB certification demonstrates study of distributed PostgreSQL.",
	},
	{
		ID:       "contact-email-pt",
		Category: "contact",
		Language: "pt",
		Content:  "Para entrar em contato com João Paulo por email, use joaopdias.dev@gmail.com.",
	},
	{
		ID:       "contact-email-en",
		Category: "contact",
		Language: "en",
		Content:  "To contact João Paulo by email, use joaopdias.dev@gmail.com.",
	},
	{
		ID:       "contact-phone-pt",
		Category: "contact",
		Language: "pt",
		Content:  "Para entrar em contato com João Paulo por telefone, use +55 (11) 93445-3236.",
	},
	{
		ID:       "contact-phone-en",
		Category: "contact",
		Language: "en",
		Content:  "To contact João Paulo by phone, use +55 (11) 93445-3236.",
	},
	{
		ID:       "contact-linkedin-pt",
		Category: "contact",
		Language: "pt",
		Content:  "Para conhecer o perfil profissional de João Paulo, acesse linkedin.com/in/joaopdias-dev.",
	},
	{
		ID:       "contact-linkedin-en",
		Category: "contact",
		Language: "en",
		Content:  "To see João Paulo's professional profile, visit linkedin.com/in/joaopdias-dev.",
	},
	{
		ID:       "contact-github-pt",
		Category: "contact",
		Language: "pt",
		Content:  "Para ver códigos e projetos de João Paulo, acesse github.com/Joaopdiasventura.",
	},
	{
		ID:       "contact-github-en",
		Category: "contact",
		Language: "en",
		Content:  "To see João Paulo's code and projects, visit github.com/Joaopdiasventura.",
	},
	{
		ID:       "service-business-automation-pt",
		Category: "service",
		Language: "pt",
		Content:  "João Paulo pode automatizar processos empresariais para substituir tarefas manuais, reduzir retrabalho e dar mais previsibilidade a operações importantes.",
	},
	{
		ID:       "service-business-automation-en",
		Category: "service",
		Language: "en",
		Content:  "João Paulo can automate business processes to replace manual tasks, reduce rework, and make important operations more predictable.",
	},
	{
		ID:       "service-financial-systems-pt",
		Category: "service",
		Language: "pt",
		Content:  "João Paulo pode desenvolver sistemas financeiros com cuidado em consistência, validação de dados, histórico de operações e confiabilidade.",
	},
	{
		ID:       "service-financial-systems-en",
		Category: "service",
		Language: "en",
		Content:  "João Paulo can build financial systems with attention to consistency, data validation, operation history, and reliability.",
	},
	{
		ID:       "service-web-applications-pt",
		Category: "service",
		Language: "pt",
		Content:  "João Paulo pode criar aplicações web para transformar processos, dados e regras de negócio em interfaces claras para usuários e equipes.",
	},
	{
		ID:       "service-web-applications-en",
		Category: "service",
		Language: "en",
		Content:  "João Paulo can build web applications that turn processes, data, and business rules into clear interfaces for users and teams.",
	},
	{
		ID:       "service-apis-internal-systems-pt",
		Category: "service",
		Language: "pt",
		Content:  "João Paulo pode desenvolver sistemas internos, APIs e automações para integrar plataformas e processar operações importantes para empresas.",
	},
	{
		ID:       "service-apis-internal-systems-en",
		Category: "service",
		Language: "en",
		Content:  "João Paulo can develop internal systems, APIs, and automations to integrate platforms and process important business operations.",
	},
	{
		ID:       "service-async-cloud-pt",
		Category: "service",
		Language: "pt",
		Content:  "João Paulo pode criar fluxos assíncronos, plataformas orientadas a eventos e infraestrutura cloud para processar tarefas em segundo plano com mais confiabilidade.",
	},
	{
		ID:       "service-async-cloud-en",
		Category: "service",
		Language: "en",
		Content:  "João Paulo can build asynchronous flows, event-driven platforms, and cloud infrastructure to process background tasks with more reliability.",
	},
	{
		ID:       "services-commercial-limitations-pt",
		Category: "service",
		Language: "pt",
		Content:  "O portfólio público de João Paulo não informa preços, prazos, disponibilidade atual, termos contratuais ou garantias de aceitação de projetos.",
	},
	{
		ID:       "services-commercial-limitations-en",
		Category: "service",
		Language: "en",
		Content:  "João Paulo's public portfolio does not state prices, timelines, current availability, contract terms, or guarantees of project acceptance.",
	},
	{
		ID:       "project-auronix-description-pt",
		Category: "project",
		Language: "pt",
		Content:  "Auronix é uma plataforma financeira full stack criada para representar operações de um banco digital.",
	},
	{
		ID:       "project-auronix-description-en",
		Category: "project",
		Language: "en",
		Content:  "Auronix is a full stack financial platform created to represent digital banking operations.",
	},
	{
		ID:       "project-auronix-consistency-pt",
		Category: "impact",
		Language: "pt",
		Content:  "No Auronix, João Paulo trabalhou com transferências confiáveis, versionamento otimista para evitar confirmações incompatíveis ao mesmo tempo e um ledger auditável para histórico verificável das movimentações.",
	},
	{
		ID:       "project-auronix-consistency-en",
		Category: "impact",
		Language: "en",
		Content:  "In Auronix, João Paulo worked with reliable transfers, optimistic versioning to prevent incompatible operations from being confirmed at the same time, and an auditable ledger for verifiable movement history.",
	},
	{
		ID:       "project-auronix-architecture-pt",
		Category: "project",
		Language: "pt",
		Content:  "O Auronix usa backend stateless para permitir várias instâncias sem depender da memória local, Redis como apoio operacional e execução distribuída para reduzir dependência de uma única máquina.",
	},
	{
		ID:       "project-auronix-architecture-en",
		Category: "project",
		Language: "en",
		Content:  "Auronix uses a stateless backend to allow multiple instances without depending on local memory, Redis for operational support, and distributed execution to reduce dependence on a single machine.",
	},
	{
		ID:       "project-auronix-infrastructure-pt",
		Category: "project",
		Language: "pt",
		Content:  "No Auronix, Docker empacota os serviços, Kubernetes organiza sua execução e Terraform descreve a infraestrutura AWS EKS por arquivos versionados.",
	},
	{
		ID:       "project-auronix-infrastructure-en",
		Category: "project",
		Language: "en",
		Content:  "In Auronix, Docker packages the services, Kubernetes organizes their execution, and Terraform describes the AWS EKS infrastructure through versioned files.",
	},
	{
		ID:       "project-auronix-technologies-pt",
		Category: "technology",
		Language: "pt",
		Content:  "O Auronix utiliza Spring Boot, Angular, PostgreSQL, RabbitMQ, Redis, Docker, Kubernetes, AWS EKS e Terraform como suporte para uma plataforma financeira distribuída.",
	},
	{
		ID:       "project-auronix-technologies-en",
		Category: "technology",
		Language: "en",
		Content:  "Auronix uses Spring Boot, Angular, PostgreSQL, RabbitMQ, Redis, Docker, Kubernetes, AWS EKS, and Terraform to support a distributed financial platform.",
	},
	{
		ID:       "project-xtube-description-pt",
		Category: "project",
		Language: "pt",
		Content:  "X Tube é um serviço de streaming desenvolvido por uma equipe de três pessoas.",
	},
	{
		ID:       "project-xtube-description-en",
		Category: "project",
		Language: "en",
		Content:  "X Tube is a streaming service developed by a team of three people.",
	},
	{
		ID:       "project-xtube-leadership-pt",
		Category: "impact",
		Language: "pt",
		Content:  "No X Tube, João Paulo teve liderança técnica no desenho do fluxo de upload, processamento e entrega de vídeos.",
	},
	{
		ID:       "project-xtube-leadership-en",
		Category: "impact",
		Language: "en",
		Content:  "In X Tube, João Paulo had technical leadership in designing the video upload, processing, and delivery flow.",
	},
	{
		ID:       "project-xtube-processing-pt",
		Category: "project",
		Language: "pt",
		Content:  "João Paulo desenvolveu em Go o serviço do X Tube responsável por receber eventos, processar vídeos com FFmpeg e salvar os artefatos gerados no Amazon S3.",
	},
	{
		ID:       "project-xtube-processing-en",
		Category: "project",
		Language: "en",
		Content:  "João Paulo developed in Go the X Tube service responsible for receiving events, processing videos with FFmpeg, and saving generated artifacts to Amazon S3.",
	},
	{
		ID:       "project-xtube-async-progress-pt",
		Category: "project",
		Language: "pt",
		Content:  "No X Tube, Amazon SQS distribui trabalhos de processamento, Kafka publica dezenas de atualizações de progresso por vídeo e Prometheus ajuda a acompanhar o funcionamento do serviço.",
	},
	{
		ID:       "project-xtube-async-progress-en",
		Category: "project",
		Language: "en",
		Content:  "In X Tube, Amazon SQS distributes processing jobs, Kafka publishes dozens of progress updates per video, and Prometheus helps monitor how the service is operating.",
	},
	{
		ID:       "project-ggcompress-description-pt",
		Category: "project",
		Language: "pt",
		Content:  "GGCompress é uma ferramenta em Go criada para compactar e arquivar arquivos grandes com velocidade, segurança e comportamento previsível.",
	},
	{
		ID:       "project-ggcompress-description-en",
		Category: "project",
		Language: "en",
		Content:  "GGCompress is a Go tool created to compress and archive large files with speed, safety, and predictable behavior.",
	},
	{
		ID:       "project-ggcompress-concurrency-pt",
		Category: "project",
		Language: "pt",
		Content:  "O GGCompress divide arquivos em chunks, que são partes menores do arquivo, e usa goroutines para processar várias tarefas de forma concorrente.",
	},
	{
		ID:       "project-ggcompress-concurrency-en",
		Category: "project",
		Language: "en",
		Content:  "GGCompress splits files into chunks, which are smaller parts of the file, and uses goroutines to process several tasks concurrently.",
	},
	{
		ID:       "project-ggcompress-integrity-pt",
		Category: "impact",
		Language: "pt",
		Content:  "O GGCompress usa checksum por chunk, SHA-256 para verificação global, operações atômicas e isolamento temporário para evitar arquivos corrompidos ou resultados incompletos.",
	},
	{
		ID:       "project-ggcompress-integrity-en",
		Category: "impact",
		Language: "en",
		Content:  "GGCompress uses per-chunk checksums, SHA-256 for global verification, atomic operations, and temporary isolation to prevent corrupted files or incomplete results.",
	},
	{
		ID:       "project-ggcompress-performance-pt",
		Category: "impact",
		Language: "pt",
		Content:  "O GGCompress alcançou throughput de até 1.23 GB/s em benchmark com arquivos de 9.77 GB.",
	},
	{
		ID:       "project-ggcompress-performance-en",
		Category: "impact",
		Language: "en",
		Content:  "GGCompress reached throughput of up to 1.23 GB/s in a benchmark with 9.77 GB files.",
	},
	{
		ID:       "project-auditex-description-pt",
		Category: "project",
		Language: "pt",
		Content:  "Auditex é um ledger financeiro full stack baseado em uma blockchain centralizada, criado para registrar eventos financeiros de forma verificável.",
	},
	{
		ID:       "project-auditex-description-en",
		Category: "project",
		Language: "en",
		Content:  "Auditex is a full stack financial ledger based on a centralized blockchain, created to record financial events in a verifiable way.",
	},
	{
		ID:       "project-auditex-integrity-pt",
		Category: "impact",
		Language: "pt",
		Content:  "O Auditex permite detectar alterações no histórico financeiro, validar a origem das operações e impedir a repetição indevida de transações.",
	},
	{
		ID:       "project-auditex-integrity-en",
		Category: "impact",
		Language: "en",
		Content:  "Auditex makes it possible to detect changes in financial history, validate the origin of operations, and prevent improper transaction replay.",
	},
	{
		ID:       "project-auditex-validation-pt",
		Category: "project",
		Language: "pt",
		Content:  "No Auditex, assinatura RSA confirma a origem da transação, nonce impede reutilização indevida, payload canônico padroniza os dados, Merkle Root resume transações e proof of work participa da validação dos blocos.",
	},
	{
		ID:       "project-auditex-validation-en",
		Category: "project",
		Language: "en",
		Content:  "In Auditex, RSA signatures confirm transaction origin, nonces prevent improper reuse, canonical payloads standardize data, Merkle Root summarizes transactions, and proof of work participates in block validation.",
	},
	{
		ID:       "project-auditex-wallet-pt",
		Category: "project",
		Language: "pt",
		Content:  "O Auditex possui dashboard com cofre local de carteira criptografado em IndexedDB, armazenando a carteira no navegador.",
	},
	{
		ID:       "project-auditex-wallet-en",
		Category: "project",
		Language: "en",
		Content:  "Auditex has a dashboard with a local encrypted wallet vault in IndexedDB, storing the wallet in the browser.",
	},
	{
		ID:       "project-auditex-technologies-pt",
		Category: "technology",
		Language: "pt",
		Content:  "O Auditex utiliza Spring Boot, Angular, PostgreSQL, RabbitMQ e IndexedDB como suporte para registro financeiro verificável.",
	},
	{
		ID:       "project-auditex-technologies-en",
		Category: "technology",
		Language: "en",
		Content:  "Auditex uses Spring Boot, Angular, PostgreSQL, RabbitMQ, and IndexedDB to support verifiable financial records.",
	},
	{
		ID:       "project-comparison-financial-pt",
		Category: "comparison",
		Language: "pt",
		Content:  "Auronix demonstra experiência de João Paulo com sistemas financeiros, consistência transacional e infraestrutura cloud.",
	},
	{
		ID:       "project-comparison-financial-en",
		Category: "comparison",
		Language: "en",
		Content:  "Auronix demonstrates João Paulo's experience with financial systems, transactional consistency, and cloud infrastructure.",
	},
	{
		ID:       "project-comparison-streaming-pt",
		Category: "comparison",
		Language: "pt",
		Content:  "X Tube demonstra experiência de João Paulo com processamento assíncrono, streaming, observabilidade e liderança técnica em uma equipe de três pessoas.",
	},
	{
		ID:       "project-comparison-streaming-en",
		Category: "comparison",
		Language: "en",
		Content:  "X Tube demonstrates João Paulo's experience with asynchronous processing, streaming, observability, and technical leadership in a three-person team.",
	},
	{
		ID:       "project-comparison-go-performance-pt",
		Category: "comparison",
		Language: "pt",
		Content:  "GGCompress demonstra experiência de João Paulo com Go, concorrência, desempenho e integridade de dados.",
	},
	{
		ID:       "project-comparison-go-performance-en",
		Category: "comparison",
		Language: "en",
		Content:  "GGCompress demonstrates João Paulo's experience with Go, concurrency, performance, and data integrity.",
	},
	{
		ID:       "project-comparison-auditability-pt",
		Category: "comparison",
		Language: "pt",
		Content:  "Auditex demonstra experiência de João Paulo com auditabilidade, criptografia e validação histórica de eventos financeiros.",
	},
	{
		ID:       "project-comparison-auditability-en",
		Category: "comparison",
		Language: "en",
		Content:  "Auditex demonstrates João Paulo's experience with auditability, cryptography, and historical validation of financial events.",
	},
	{
		ID:       "project-comparison-best-pt",
		Category: "comparison",
		Language: "pt",
		Content:  "Os projetos prioritários de João Paulo são Auronix, X Tube, GGCompress e Auditex; cada um demonstra uma capacidade profissional diferente.",
	},
	{
		ID:       "project-comparison-best-en",
		Category: "comparison",
		Language: "en",
		Content:  "João Paulo's priority projects are Auronix, X Tube, GGCompress, and Auditex; each one demonstrates a different professional capability.",
	},
}

var staticDocumentPointers = documentPointers()

func Documents() []*domain.Document {
	return staticDocumentPointers
}

func documentPointers() []*domain.Document {
	documents := make([]*domain.Document, 0, len(staticDocuments))

	for index := range staticDocuments {
		applyDocumentMetadata(&staticDocuments[index])
		documents = append(documents, &staticDocuments[index])
	}

	return documents
}
