package knowledge

import "ai-agent/internal/domain"

var staticDocuments = [...]domain.Document{
	{
		ID:       "identity-basic-pt",
		Category: "identity",
		Language: "pt",
		Content:  "João Paulo Dias Ventura é um desenvolvedor de software de São Paulo que cria sistemas digitais para empresas.",
	},
	{
		ID:       "identity-professional-summary-pt",
		Category: "identity",
		Language: "pt",
		Content:  "João Paulo cria sistemas digitais confiáveis, principalmente para empresas que precisam automatizar processos importantes e lidar com muitos dados.",
	},
	{
		ID:       "profile-focus-pt",
		Category: "profile",
		Language: "pt",
		Content:  "João Paulo gosta de transformar processos complexos em sistemas organizados, seguros e fáceis de acompanhar.",
	},
	{
		ID:       "profile-backend-technologies-pt",
		Category: "technology",
		Language: "pt",
		Content:  "João Paulo trabalha na parte dos sistemas que fica por trás das telas, usando Node.js, TypeScript, NestJS, Fastify, Java, Spring Boot e Go.",
	},
	{
		ID:       "profile-frontend-technologies-pt",
		Category: "technology",
		Language: "pt",
		Content:  "João Paulo também desenvolve interfaces web com Angular, buscando páginas rápidas, organizadas e agradáveis de usar.",
	},
	{
		ID:       "profile-database-technologies-pt",
		Category: "technology",
		Language: "pt",
		Content:  "João Paulo trabalha com armazenamento de informações usando PostgreSQL, MongoDB, Redis e Amazon S3.",
	},
	{
		ID:       "profile-messaging-technologies-pt",
		Category: "technology",
		Language: "pt",
		Content:  "João Paulo cria sistemas que trocam informações em tempo real, usando RabbitMQ, BullMQ, WebSocket, SSE e AsyncAPI.",
	},
	{
		ID:       "profile-infrastructure-technologies-pt",
		Category: "technology",
		Language: "pt",
		Content:  "João Paulo sabe colocar aplicações no ar e organizar ambientes usando AWS, S3, ECS, IAM, Docker Compose, nginx e pipelines de CI/CD.",
	},
	{
		ID:       "profile-mobile-technologies-pt",
		Category: "technology",
		Language: "pt",
		Content:  "João Paulo consegue criar aplicações para celular com Capacitor e aplicações para computador com Tauri.",
	},
	{
		ID:       "profile-language-pt",
		Category: "profile",
		Language: "pt",
		Content:  "João Paulo possui inglês avançado.",
	},
	{
		ID:       "profile-availability-pt",
		Category: "profile",
		Language: "pt",
		Content:  "João Paulo está aberto a oportunidades em que possa criar sistemas importantes para o negócio, especialmente automações, produtos digitais e plataformas internas.",
	},
	{
		ID:       "profile-delivery-style-pt",
		Category: "profile",
		Language: "pt",
		Content:  "João Paulo costuma conectar backend, frontend, infraestrutura e dados para entregar sistemas completos, não apenas partes isoladas.",
	},
	{
		ID:       "profile-business-impact-pt",
		Category: "impact",
		Language: "pt",
		Content:  "A experiência pública de João Paulo inclui automação de faturamento, preparação de dados para inteligência artificial e projetos com testes automatizados.",
	},
	{
		ID:       "career-first-job-pt",
		Category: "career",
		Language: "pt",
		Content:  "O primeiro emprego de João Paulo foi como estagiário em desenvolvimento de sistemas na Representa Online entre junho e agosto de 2024.",
	},
	{
		ID:       "career-current-job-pt",
		Category: "career",
		Language: "pt",
		Content:  "João Paulo trabalha atualmente como desenvolvedor pleno na uFind Tecnologia desde junho de 2025.",
	},
	{
		ID:       "career-current-activities-pt",
		Category: "career",
		Language: "pt",
		Content:  "Na uFind Tecnologia, João Paulo desenvolve um sistema que automatiza o faturamento de seguros e ajuda a acompanhar cada etapa do processo.",
	},
	{
		ID:       "career-current-impact-pt",
		Category: "career",
		Language: "pt",
		Content:  "Na uFind Tecnologia, João Paulo ajudou a automatizar mais de um milhão de reais por mês em faturamento, reduzindo tarefas manuais de dias para minutos.",
	},
	{
		ID:       "career-current-architecture-pt",
		Category: "career",
		Language: "pt",
		Content:  "Na uFind Tecnologia, João Paulo criou formas de receber e validar diferentes arquivos financeiros sem depender de trabalho manual repetitivo.",
	},
	{
		ID:       "career-current-aws-pt",
		Category: "career",
		Language: "pt",
		Content:  "Na uFind Tecnologia, João Paulo ajudou a organizar aplicações e arquivos na AWS usando S3, ECS e IAM.",
	},
	{
		ID:       "career-junior-job-pt",
		Category: "career",
		Language: "pt",
		Content:  "João Paulo trabalhou como desenvolvedor júnior na Representa Online entre setembro de 2024 e maio de 2025.",
	},
	{
		ID:       "career-junior-data-pipelines-pt",
		Category: "career",
		Language: "pt",
		Content:  "Na Representa Online, João Paulo criou automações que prepararam mais de 16 GB de conteúdo de televisão para uso com inteligência artificial.",
	},
	{
		ID:       "career-junior-realtime-pt",
		Category: "career",
		Language: "pt",
		Content:  "Na Representa Online, João Paulo criou recursos em tempo real e integrou sistemas com a API da OpenAI.",
	},
	{
		ID:       "career-intern-activities-pt",
		Category: "career",
		Language: "pt",
		Content:  "Como estagiário na Representa Online, João Paulo ajudou a criar recursos de catálogo, busca de conteúdo e login de usuários.",
	},
	{
		ID:       "career-intern-search-pt",
		Category: "career",
		Language: "pt",
		Content:  "Como estagiário, João Paulo criou uma busca por proximidade para ajudar usuários a encontrar conteúdos ou opções próximas.",
	},
	{
		ID:       "career-intern-authentication-pt",
		Category: "career",
		Language: "pt",
		Content:  "Como estagiário, João Paulo trabalhou em recursos de login, incluindo acesso com conta Google.",
	},
	{
		ID:       "career-intern-frontend-pt",
		Category: "career",
		Language: "pt",
		Content:  "Como estagiário, João Paulo melhorou páginas web para que carregassem mais rápido e oferecessem uma experiência melhor ao usuário.",
	},
	{
		ID:       "education-fiap-pt",
		Category: "education",
		Language: "pt",
		Content:  "João Paulo cursa Inteligência Artificial na FIAP entre 2026 e 2028.",
	},
	{
		ID:       "education-etec-pt",
		Category: "education",
		Language: "pt",
		Content:  "João Paulo cursou Desenvolvimento de Sistemas na Etec Guarulhos entre 2023 e 2025.",
	},
	{
		ID:       "certificate-aws-pt",
		Category: "certificate",
		Language: "pt",
		Content:  "João Paulo possui certificação da AWS relacionada à criação e publicação de sistemas em nuvem.",
	},
	{
		ID:       "certificate-mongodb-pt",
		Category: "certificate",
		Language: "pt",
		Content:  "João Paulo possui certificação da MongoDB com foco em tecnologia para serviços financeiros.",
	},
	{
		ID:       "contact-email-pt",
		Category: "contact",
		Language: "pt",
		Content:  "Para entrar em contato com João Paulo por email, use joaopdias.dev@gmail.com.",
	},
	{
		ID:       "contact-phone-pt",
		Category: "contact",
		Language: "pt",
		Content:  "Para entrar em contato com João Paulo por telefone, use +55 (11) 98655-3558.",
	},
	{
		ID:       "contact-linkedin-pt",
		Category: "contact",
		Language: "pt",
		Content:  "Para conhecer o perfil profissional de João Paulo, acesse linkedin.com/in/joaopdias-dev.",
	},
	{
		ID:       "contact-github-pt",
		Category: "contact",
		Language: "pt",
		Content:  "Para ver códigos e projetos de João Paulo, acesse github.com/Joaopdiasventura.",
	},
	{
		ID:       "contact-public-channels-pt",
		Category: "contact",
		Language: "pt",
		Content:  "Os canais públicos de contato de João Paulo incluem email, telefone, LinkedIn e GitHub.",
	},
	{
		ID:       "services-web-pt",
		Category: "service",
		Language: "pt",
		Content:  "João Paulo pode desenvolver sites e aplicações web rápidas, organizadas e fáceis de usar.",
	},
	{
		ID:       "services-backend-pt",
		Category: "service",
		Language: "pt",
		Content:  "João Paulo pode desenvolver a parte interna de sistemas, APIs, automações, integrações e aplicações em tempo real.",
	},
	{
		ID:       "services-mobile-pt",
		Category: "service",
		Language: "pt",
		Content:  "João Paulo pode desenvolver aplicativos para celular e também aplicações para computador.",
	},
	{
		ID:       "services-business-systems-pt",
		Category: "service",
		Language: "pt",
		Content:  "João Paulo pode desenvolver painéis, sistemas administrativos, áreas de login, catálogos e fluxos de pagamento ou operação.",
	},
	{
		ID:       "services-data-pt",
		Category: "service",
		Language: "pt",
		Content:  "João Paulo pode criar automações, integrações entre sistemas e fluxos que organizam dados para uso com inteligência artificial.",
	},
	{
		ID:       "services-commercial-limitations-pt",
		Category: "service",
		Language: "pt",
		Content:  "O portfólio público de João Paulo não informa preços, prazos, disponibilidade atual, termos contratuais ou garantias de aceitação de projetos.",
	},
	{
		ID:       "project-auronix-description-pt",
		Category: "project",
		Language: "pt",
		Content:  "Auronix é um projeto de banco digital criado para simular transferências, acompanhar movimentações e mostrar atualizações em tempo real.",
	},
	{
		ID:       "project-auronix-technologies-pt",
		Category: "project",
		Language: "pt",
		Content:  "No Auronix, João usou NestJS, Fastify, PostgreSQL, Redis, BullMQ, Angular e SSE para criar uma experiência parecida com a de um banco digital.",
	},
	{
		ID:       "project-auronix-architecture-pt",
		Category: "project",
		Language: "pt",
		Content:  "O Auronix foi pensado para evitar conflitos em operações financeiras e mostrar ao usuário o andamento das transações em tempo real.",
	},
	{
		ID:       "project-auronix-metrics-pt",
		Category: "impact",
		Language: "pt",
		Content:  "O Auronix possui 248 testes automatizados e regras para expirar solicitações, reforçando a confiabilidade do projeto.",
	},
	{
		ID:       "project-auronix-impact-pt",
		Category: "impact",
		Language: "pt",
		Content:  "O Auronix mostra experiência de João Paulo com fluxos financeiros, atualização em tempo real e cuidado com consistência de transações.",
	},
	{
		ID:       "project-modularis-description-pt",
		Category: "project",
		Language: "pt",
		Content:  "Modularis é uma plataforma que divide um sistema grande em partes menores para organizar login, pagamentos e ativação de planos premium.",
	},
	{
		ID:       "project-modularis-technologies-pt",
		Category: "project",
		Language: "pt",
		Content:  "No Modularis, João usou NestJS, Spring Boot, Go, RabbitMQ, PostgreSQL, MongoDB, Docker Compose, nginx e AsyncAPI.",
	},
	{
		ID:       "project-modularis-metrics-pt",
		Category: "impact",
		Language: "pt",
		Content:  "O Modularis mostra a capacidade de João de organizar sistemas grandes em vários serviços que trabalham juntos.",
	},
	{
		ID:       "project-modularis-impact-pt",
		Category: "impact",
		Language: "pt",
		Content:  "O Modularis evidencia experiência de João Paulo em sistemas distribuídos, pagamentos, login e comunicação entre serviços.",
	},
	{
		ID:       "project-votrix-description-pt",
		Category: "project",
		Language: "pt",
		Content:  "Votrix é um projeto em TypeScript criado para estudar como servidores web podem responder mais rápido.",
	},
	{
		ID:       "project-votrix-technologies-pt",
		Category: "project",
		Language: "pt",
		Content:  "No Votrix, João usou TypeScript, node:http e autocannon para medir e melhorar desempenho.",
	},
	{
		ID:       "project-votrix-performance-pt",
		Category: "impact",
		Language: "pt",
		Content:  "O Votrix alcançou mais de 30 mil requisições por segundo em testes, mostrando foco em velocidade e eficiência.",
	},
	{
		ID:       "project-ggcompress-description-pt",
		Category: "project",
		Language: "pt",
		Content:  "GGCompress é uma ferramenta em Go criada para compactar e organizar arquivos grandes de forma rápida e confiável.",
	},
	{
		ID:       "project-ggcompress-technologies-pt",
		Category: "project",
		Language: "pt",
		Content:  "No GGCompress, João usou Go, goroutines, channels, gzip, SHA-256 e CLI para lidar com arquivos grandes pelo terminal.",
	},
	{
		ID:       "project-ggcompress-integrity-pt",
		Category: "impact",
		Language: "pt",
		Content:  "O GGCompress verifica se os arquivos continuam íntegros depois do processamento, usando SHA-256.",
	},
	{
		ID:       "project-ggcompress-performance-pt",
		Category: "impact",
		Language: "pt",
		Content:  "O GGCompress conseguiu processar quase 10 GiB de dados com alta velocidade em testes controlados.",
	},
	{
		ID:       "project-vox-description-pt",
		Category: "project",
		Language: "pt",
		Content:  "VOX é uma plataforma de votação criada para manter clareza, segurança e confiança mesmo com muitos usuários ao mesmo tempo.",
	},
	{
		ID:       "project-vox-technologies-pt",
		Category: "project",
		Language: "pt",
		Content:  "No VOX, João usou Tauri, NestJS e Redis para criar uma experiência de votação rápida e organizada.",
	},
	{
		ID:       "project-vox-metrics-pt",
		Category: "impact",
		Language: "pt",
		Content:  "O VOX foi testado para suportar mais de 500 usuários ao mesmo tempo e possui 108 testes automatizados.",
	},
	{
		ID:       "project-etecfy-description-pt",
		Category: "project",
		Language: "pt",
		Content:  "Etecfy é uma plataforma de música criada para permitir descoberta de faixas, crescimento de catálogo e reprodução contínua.",
	},
	{
		ID:       "project-etecfy-technologies-pt",
		Category: "project",
		Language: "pt",
		Content:  "No Etecfy, João usou Angular, NestJS e Capacitor para entregar a experiência em web e celular.",
	},
	{
		ID:       "project-etecfy-metrics-pt",
		Category: "impact",
		Language: "pt",
		Content:  "O Etecfy recebeu 1,3 mil acessos nas primeiras seis horas, mostrando boa recepção inicial do projeto.",
	},
	{
		ID:       "project-comparison-financial-pt",
		Category: "comparison",
		Language: "pt",
		Content:  "Para mostrar experiência com sistemas financeiros, o melhor exemplo público de João Paulo é o Auronix.",
	},
	{
		ID:       "project-comparison-distributed-pt",
		Category: "comparison",
		Language: "pt",
		Content:  "Para mostrar organização de sistemas grandes e divididos em partes, o melhor exemplo público de João Paulo é o Modularis.",
	},
	{
		ID:       "project-comparison-http-performance-pt",
		Category: "comparison",
		Language: "pt",
		Content:  "Para mostrar foco em velocidade de servidores web, o melhor exemplo público de João Paulo é o Votrix.",
	},
	{
		ID:       "project-comparison-go-performance-pt",
		Category: "comparison",
		Language: "pt",
		Content:  "Para mostrar habilidade com Go e processamento de arquivos grandes, o melhor exemplo público de João Paulo é o GGCompress.",
	},
	{
		ID:       "project-comparison-auditability-pt",
		Category: "comparison",
		Language: "pt",
		Content:  "Para mostrar cuidado com confiança e segurança em votações, o melhor exemplo público de João Paulo é o VOX.",
	},
	{
		ID:       "project-comparison-streaming-pt",
		Category: "comparison",
		Language: "pt",
		Content:  "Para mostrar experiência com produto digital e música por streaming, o melhor exemplo público de João Paulo é o Etecfy.",
	},
	{
		ID:       "project-comparison-best-pt",
		Category: "comparison",
		Language: "pt",
		Content:  "João Paulo já fez projetos como Auronix, Modularis, Votrix, GGCompress, VOX e Etecfy; cada um mostra uma habilidade diferente.",
	},
	{
		ID:       "identity-basic-en",
		Category: "identity",
		Language: "en",
		Content:  "João Paulo Dias Ventura is a software developer from São Paulo who builds digital systems for companies.",
	},
	{
		ID:       "identity-professional-summary-en",
		Category: "identity",
		Language: "en",
		Content:  "João Paulo builds reliable digital systems, especially for companies that need to automate important processes and handle a lot of data.",
	},
	{
		ID:       "profile-focus-en",
		Category: "profile",
		Language: "en",
		Content:  "João Paulo likes turning complex processes into organized, secure systems that are easy to follow.",
	},
	{
		ID:       "profile-backend-technologies-en",
		Category: "technology",
		Language: "en",
		Content:  "João Paulo works on the behind-the-scenes part of systems using Node.js, TypeScript, NestJS, Fastify, Java, Spring Boot, and Go.",
	},
	{
		ID:       "profile-frontend-technologies-en",
		Category: "technology",
		Language: "en",
		Content:  "João Paulo also builds web interfaces with Angular, focusing on fast, organized, and pleasant pages.",
	},
	{
		ID:       "profile-database-technologies-en",
		Category: "technology",
		Language: "en",
		Content:  "João Paulo works with data storage using PostgreSQL, MongoDB, Redis, and Amazon S3.",
	},
	{
		ID:       "profile-messaging-technologies-en",
		Category: "technology",
		Language: "en",
		Content:  "João Paulo builds systems that exchange information in real time using RabbitMQ, BullMQ, WebSocket, SSE, and AsyncAPI.",
	},
	{
		ID:       "profile-infrastructure-technologies-en",
		Category: "technology",
		Language: "en",
		Content:  "João Paulo knows how to publish applications and organize environments using AWS, S3, ECS, IAM, Docker Compose, nginx, and CI/CD pipelines.",
	},
	{
		ID:       "profile-mobile-technologies-en",
		Category: "technology",
		Language: "en",
		Content:  "João Paulo can build mobile apps with Capacitor and desktop apps with Tauri.",
	},
	{
		ID:       "profile-language-en",
		Category: "profile",
		Language: "en",
		Content:  "João Paulo has advanced English skills.",
	},
	{
		ID:       "profile-availability-en",
		Category: "profile",
		Language: "en",
		Content:  "João Paulo is open to opportunities where he can build important business systems, especially automations, digital products, and internal platforms.",
	},
	{
		ID:       "profile-delivery-style-en",
		Category: "profile",
		Language: "en",
		Content:  "João Paulo tends to connect backend, frontend, infrastructure, and data work to deliver complete systems, not only isolated parts.",
	},
	{
		ID:       "profile-business-impact-en",
		Category: "impact",
		Language: "en",
		Content:  "João Paulo's public experience includes billing automation, data preparation for artificial intelligence, and projects with automated tests.",
	},
	{
		ID:       "career-first-job-en",
		Category: "career",
		Language: "en",
		Content:  "João Paulo's first job was as a systems development intern at Representa Online between June and August 2024.",
	},
	{
		ID:       "career-current-job-en",
		Category: "career",
		Language: "en",
		Content:  "João Paulo currently works as a mid-level developer at uFind Tecnologia, where he has been since June 2025.",
	},
	{
		ID:       "career-current-activities-en",
		Category: "career",
		Language: "en",
		Content:  "At uFind Tecnologia, João Paulo develops a system that automates insurance billing and helps track each step of the process.",
	},
	{
		ID:       "career-current-impact-en",
		Category: "career",
		Language: "en",
		Content:  "At uFind Tecnologia, João Paulo helped automate more than one million reais per month in billing, reducing manual tasks from days to minutes.",
	},
	{
		ID:       "career-current-architecture-en",
		Category: "career",
		Language: "en",
		Content:  "At uFind Tecnologia, João Paulo created ways to receive and validate different financial files without relying on repetitive manual work.",
	},
	{
		ID:       "career-current-aws-en",
		Category: "career",
		Language: "en",
		Content:  "At uFind Tecnologia, João Paulo helped organize applications and files on AWS using S3, ECS, and IAM.",
	},
	{
		ID:       "career-junior-job-en",
		Category: "career",
		Language: "en",
		Content:  "João Paulo worked as a junior developer at Representa Online between September 2024 and May 2025.",
	},
	{
		ID:       "career-junior-data-pipelines-en",
		Category: "career",
		Language: "en",
		Content:  "At Representa Online, João Paulo created automations that prepared more than 16 GB of television content for use with artificial intelligence.",
	},
	{
		ID:       "career-junior-realtime-en",
		Category: "career",
		Language: "en",
		Content:  "At Representa Online, João Paulo built real-time features and integrated systems with the OpenAI API.",
	},
	{
		ID:       "career-intern-activities-en",
		Category: "career",
		Language: "en",
		Content:  "As an intern at Representa Online, João Paulo helped build catalog, content discovery, and user login features.",
	},
	{
		ID:       "career-intern-search-en",
		Category: "career",
		Language: "en",
		Content:  "As an intern, João Paulo created a proximity search to help users find nearby content or options.",
	},
	{
		ID:       "career-intern-authentication-en",
		Category: "career",
		Language: "en",
		Content:  "As an intern, João Paulo worked on login features, including access with a Google account.",
	},
	{
		ID:       "career-intern-frontend-en",
		Category: "career",
		Language: "en",
		Content:  "As an intern, João Paulo improved web pages so they loaded faster and offered a better user experience.",
	},
	{
		ID:       "education-fiap-en",
		Category: "education",
		Language: "en",
		Content:  "João Paulo studies Artificial Intelligence at FIAP between 2026 and 2028.",
	},
	{
		ID:       "education-etec-en",
		Category: "education",
		Language: "en",
		Content:  "João Paulo studied Systems Development at Etec Guarulhos between 2023 and 2025.",
	},
	{
		ID:       "certificate-aws-en",
		Category: "certificate",
		Language: "en",
		Content:  "João Paulo has an AWS certification related to building and publishing systems in the cloud.",
	},
	{
		ID:       "certificate-mongodb-en",
		Category: "certificate",
		Language: "en",
		Content:  "João Paulo has a MongoDB certification focused on technology for financial services.",
	},
	{
		ID:       "contact-email-en",
		Category: "contact",
		Language: "en",
		Content:  "To contact João Paulo by email, use joaopdias.dev@gmail.com.",
	},
	{
		ID:       "contact-phone-en",
		Category: "contact",
		Language: "en",
		Content:  "To contact João Paulo by phone, use +55 (11) 98655-3558.",
	},
	{
		ID:       "contact-linkedin-en",
		Category: "contact",
		Language: "en",
		Content:  "To see João Paulo's professional profile, visit linkedin.com/in/joaopdias-dev.",
	},
	{
		ID:       "contact-github-en",
		Category: "contact",
		Language: "en",
		Content:  "To see João Paulo's code and projects, visit github.com/Joaopdiasventura.",
	},
	{
		ID:       "contact-public-channels-en",
		Category: "contact",
		Language: "en",
		Content:  "João Paulo's public contact channels include email, phone, LinkedIn, and GitHub.",
	},
	{
		ID:       "services-web-en",
		Category: "service",
		Language: "en",
		Content:  "João Paulo can build fast, organized, and easy-to-use websites and web applications.",
	},
	{
		ID:       "services-backend-en",
		Category: "service",
		Language: "en",
		Content:  "João Paulo can build the internal part of systems, APIs, automations, integrations, and real-time applications.",
	},
	{
		ID:       "services-mobile-en",
		Category: "service",
		Language: "en",
		Content:  "João Paulo can build mobile apps and desktop applications.",
	},
	{
		ID:       "services-business-systems-en",
		Category: "service",
		Language: "en",
		Content:  "João Paulo can build dashboards, admin systems, login areas, catalogs, and payment or operation flows.",
	},
	{
		ID:       "services-data-en",
		Category: "service",
		Language: "en",
		Content:  "João Paulo can create automations, system integrations, and flows that organize data for use with artificial intelligence.",
	},
	{
		ID:       "services-commercial-limitations-en",
		Category: "service",
		Language: "en",
		Content:  "João Paulo's public portfolio does not state prices, timelines, current availability, contract terms, or guarantees of project acceptance.",
	},
	{
		ID:       "project-auronix-description-en",
		Category: "project",
		Language: "en",
		Content:  "Auronix is a digital banking project built to simulate transfers, track financial movements, and show real-time updates.",
	},
	{
		ID:       "project-auronix-technologies-en",
		Category: "project",
		Language: "en",
		Content:  "In Auronix, João used NestJS, Fastify, PostgreSQL, Redis, BullMQ, Angular, and SSE to create an experience similar to a digital bank.",
	},
	{
		ID:       "project-auronix-architecture-en",
		Category: "project",
		Language: "en",
		Content:  "Auronix was designed to avoid conflicts in financial operations and show users the progress of transactions in real time.",
	},
	{
		ID:       "project-auronix-metrics-en",
		Category: "impact",
		Language: "en",
		Content:  "Auronix has 248 automated tests and rules for expiring requests, reinforcing the reliability of the project.",
	},
	{
		ID:       "project-auronix-impact-en",
		Category: "impact",
		Language: "en",
		Content:  "Auronix shows João Paulo's experience with financial flows, real-time updates, and transaction consistency.",
	},
	{
		ID:       "project-modularis-description-en",
		Category: "project",
		Language: "en",
		Content:  "Modularis is a platform that splits a large system into smaller parts to organize login, payments, and premium plan activation.",
	},
	{
		ID:       "project-modularis-technologies-en",
		Category: "project",
		Language: "en",
		Content:  "In Modularis, João used NestJS, Spring Boot, Go, RabbitMQ, PostgreSQL, MongoDB, Docker Compose, nginx, and AsyncAPI.",
	},
	{
		ID:       "project-modularis-metrics-en",
		Category: "impact",
		Language: "en",
		Content:  "Modularis shows João's ability to organize large systems into several services that work together.",
	},
	{
		ID:       "project-modularis-impact-en",
		Category: "impact",
		Language: "en",
		Content:  "Modularis highlights João Paulo's experience with distributed systems, payments, login, and service-to-service communication.",
	},
	{
		ID:       "project-votrix-description-en",
		Category: "project",
		Language: "en",
		Content:  "Votrix is a TypeScript project created to study how web servers can respond faster.",
	},
	{
		ID:       "project-votrix-technologies-en",
		Category: "project",
		Language: "en",
		Content:  "In Votrix, João used TypeScript, node:http, and autocannon to measure and improve performance.",
	},
	{
		ID:       "project-votrix-performance-en",
		Category: "impact",
		Language: "en",
		Content:  "Votrix reached more than 30 thousand requests per second in tests, showing a focus on speed and efficiency.",
	},
	{
		ID:       "project-ggcompress-description-en",
		Category: "project",
		Language: "en",
		Content:  "GGCompress is a Go tool created to compress and organize large files quickly and reliably.",
	},
	{
		ID:       "project-ggcompress-technologies-en",
		Category: "project",
		Language: "en",
		Content:  "In GGCompress, João used Go, goroutines, channels, gzip, SHA-256, and CLI to handle large files from the terminal.",
	},
	{
		ID:       "project-ggcompress-integrity-en",
		Category: "impact",
		Language: "en",
		Content:  "GGCompress checks whether files remain intact after processing by using SHA-256.",
	},
	{
		ID:       "project-ggcompress-performance-en",
		Category: "impact",
		Language: "en",
		Content:  "GGCompress processed almost 10 GiB of data at high speed in controlled tests.",
	},
	{
		ID:       "project-vox-description-en",
		Category: "project",
		Language: "en",
		Content:  "VOX is a voting platform built to keep clarity, security, and trust even with many users at the same time.",
	},
	{
		ID:       "project-vox-technologies-en",
		Category: "project",
		Language: "en",
		Content:  "In VOX, João used Tauri, NestJS, and Redis to create a fast and organized voting experience.",
	},
	{
		ID:       "project-vox-metrics-en",
		Category: "impact",
		Language: "en",
		Content:  "VOX was tested to support more than 500 users at the same time and has 108 automated tests.",
	},
	{
		ID:       "project-etecfy-description-en",
		Category: "project",
		Language: "en",
		Content:  "Etecfy is a music platform built for track discovery, catalog growth, and continuous playback.",
	},
	{
		ID:       "project-etecfy-technologies-en",
		Category: "project",
		Language: "en",
		Content:  "In Etecfy, João used Angular, NestJS, and Capacitor to deliver the experience on web and mobile.",
	},
	{
		ID:       "project-etecfy-metrics-en",
		Category: "impact",
		Language: "en",
		Content:  "Etecfy received 1.3 thousand visits in its first six hours, showing good initial reception for the project.",
	},
	{
		ID:       "project-comparison-financial-en",
		Category: "comparison",
		Language: "en",
		Content:  "To show experience with financial systems, João Paulo's best public example is Auronix.",
	},
	{
		ID:       "project-comparison-distributed-en",
		Category: "comparison",
		Language: "en",
		Content:  "To show organization of large systems split into parts, João Paulo's best public example is Modularis.",
	},
	{
		ID:       "project-comparison-http-performance-en",
		Category: "comparison",
		Language: "en",
		Content:  "To show focus on web server speed, João Paulo's best public example is Votrix.",
	},
	{
		ID:       "project-comparison-go-performance-en",
		Category: "comparison",
		Language: "en",
		Content:  "To show skill with Go and large file processing, João Paulo's best public example is GGCompress.",
	},
	{
		ID:       "project-comparison-auditability-en",
		Category: "comparison",
		Language: "en",
		Content:  "To show care with trust and security in voting systems, João Paulo's best public example is VOX.",
	},
	{
		ID:       "project-comparison-streaming-en",
		Category: "comparison",
		Language: "en",
		Content:  "To show experience with digital products and music streaming, João Paulo's best public example is Etecfy.",
	},
	{
		ID:       "project-comparison-best-en",
		Category: "comparison",
		Language: "en",
		Content:  "João Paulo has built projects such as Auronix, Modularis, Votrix, GGCompress, VOX, and Etecfy; each one shows a different skill.",
	},
}

var staticDocumentPointers = documentPointers()

func Documents() []*domain.Document {
	return staticDocumentPointers
}

func documentPointers() []*domain.Document {
	documents := make([]*domain.Document, 0, len(staticDocuments))

	for index := range staticDocuments {
		documents = append(documents, &staticDocuments[index])
	}

	return documents
}
