package ontology

import "ai-agent/internal/domain"

func allConcepts() []domain.Concept {
	return []domain.Concept{
		concept(ConceptLocation, "localização", "location", nil,
			[]string{"local", "cidade", "mora", "reside"},
			[]string{"city", "based", "lives"},
		),
		concept(ConceptFinancialSystems, "sistemas financeiros", "financial systems", nil,
			[]string{"sistema financeiro", "financeiro", "finanças", "banco", "banco digital"},
			[]string{"financial system", "finance", "banking", "bank", "digital bank"},
		),
		concept(ConceptDataProcessing, "processamento de dados", "data processing", nil,
			[]string{"processamento", "processar dados"},
			[]string{"processing", "processing data"},
		),
		concept(ConceptAsyncProcessing, "processamento assíncrono", "asynchronous processing",
			[]domain.ConceptID{ConceptDataProcessing},
			[]string{"processamento assincrono", "assíncrono", "assincrono", "tarefas assíncronas"},
			[]string{"async processing", "asynchronous", "async work"},
		),
		concept(ConceptDataPipelines, "pipelines de dados", "data pipelines",
			[]domain.ConceptID{ConceptDataProcessing},
			[]string{"pipeline", "pipelines", "pipeline de dados"},
			[]string{"pipeline", "pipelines", "data pipeline"},
		),
		concept(ConceptArtificialIntelligence, "inteligência artificial", "artificial intelligence", nil,
			[]string{"ia", "agente de ia", "sistemas de ia"},
			[]string{"ai", "ai agent", "ai systems"},
		),
		concept(ConceptConsistency, "consistência", "consistency", nil,
			[]string{"consistente"},
			[]string{"consistent"},
		),
		concept(ConceptTransactionalConsistency, "consistência transacional", "transactional consistency",
			[]domain.ConceptID{ConceptConsistency},
			[]string{"consistencia transacional", "consistência de transações", "consistencia de transacoes"},
			[]string{"transaction consistency", "transactional integrity"},
		),
		concept(ConceptOptimisticLocking, "versionamento otimista", "optimistic locking",
			[]domain.ConceptID{ConceptTransactionalConsistency},
			[]string{"locking otimista", "lock otimista", "controle otimista"},
			[]string{"optimistic versioning", "optimistic concurrency control"},
		),
		concept(ConceptAuditability, "auditabilidade", "auditability", nil,
			[]string{"auditável", "auditavel", "rastreabilidade", "rastreável"},
			[]string{"auditable", "traceability", "traceable"},
		),
		concept(ConceptReliability, "confiabilidade", "reliability", nil,
			[]string{"confiável", "confiavel", "resiliência", "resiliencia", "estabilidade"},
			[]string{"reliable", "resilience", "stability"},
		),
		concept(ConceptPerformance, "performance", "performance", nil,
			[]string{"desempenho", "velocidade", "alto desempenho"},
			[]string{"speed", "high performance"},
		),
		concept(ConceptOperationalEfficiency, "eficiência operacional", "operational efficiency",
			[]domain.ConceptID{ConceptPerformance},
			[]string{"eficiencia operacional", "eficiência", "eficiencia"},
			[]string{"efficiency", "operational improvement"},
		),
		concept(ConceptContact, "contato", "contact", nil,
			[]string{"contatos"},
			[]string{"contact information", "contact details"},
		),
		concept(ConceptEmail, "e-mail", "email",
			[]domain.ConceptID{ConceptContact},
			[]string{"email", "correio eletrônico"},
			[]string{"e-mail", "mail"},
		),
		concept(ConceptPhone, "telefone", "phone",
			[]domain.ConceptID{ConceptContact},
			[]string{"celular", "número de telefone"},
			[]string{"phone number", "mobile", "cellphone"},
		),
		concept(ConceptSoftwareDevelopment, "desenvolvimento de software", "software development", nil,
			[]string{"desenvolvimento", "engenharia de software"},
			[]string{"development", "software engineering"},
		),
		concept(ConceptFrontend, "frontend", "frontend",
			[]domain.ConceptID{ConceptSoftwareDevelopment},
			[]string{"front-end", "interface"},
			[]string{"front-end", "client side", "user interface"},
		),
		concept(ConceptBackend, "backend", "backend",
			[]domain.ConceptID{ConceptSoftwareDevelopment},
			[]string{"back-end", "servidor", "api"},
			[]string{"back-end", "server side", "api"},
		),
		concept(ConceptDatabase, "banco de dados", "database", nil,
			[]string{"bancos de dados", "persistência", "persistencia"},
			[]string{"databases", "data store", "persistence"},
		),
		concept(ConceptMessaging, "mensageria", "messaging", nil,
			[]string{"fila", "filas", "mensagens", "message broker"},
			[]string{"message queue", "queues", "broker", "message broker"},
		),
		concept(ConceptDevOps, "devops", "devops", nil,
			[]string{"operações", "operacoes", "ci cd"},
			[]string{"operations", "ci cd"},
		),
		concept(ConceptInfrastructure, "infraestrutura", "infrastructure", nil,
			[]string{"infra"},
			[]string{"infra"},
		),
		concept(ConceptInfrastructureAsCode, "infraestrutura como código", "infrastructure as code",
			[]domain.ConceptID{ConceptInfrastructure, ConceptDevOps},
			[]string{"infraestrutura como codigo", "iac"},
			[]string{"iac"},
		),
		concept(ConceptOrchestration, "orquestração", "orchestration",
			[]domain.ConceptID{ConceptInfrastructure},
			[]string{"orquestracao", "orquestrar"},
			[]string{"orchestrating"},
		),
		concept(ConceptContainerization, "conteinerização", "containerization",
			[]domain.ConceptID{ConceptDevOps},
			[]string{"conteinerizacao", "containerização", "containerizacao"},
			[]string{"containerisation"},
		),
		concept(ConceptContainers, "containers", "containers",
			[]domain.ConceptID{ConceptContainerization},
			[]string{"contêineres", "conteineres"},
			[]string{"container"},
		),
		concept(ConceptCloud, "cloud", "cloud",
			[]domain.ConceptID{ConceptInfrastructure},
			[]string{"nuvem", "computação em nuvem"},
			[]string{"cloud computing"},
		),
		concept(ConceptAWS, "aws", "aws",
			[]domain.ConceptID{ConceptCloud},
			[]string{"amazon web services"},
			[]string{"amazon web services"},
		),
		concept(ConceptKubernetes, "kubernetes", "kubernetes",
			[]domain.ConceptID{ConceptOrchestration},
			[]string{"k8s"},
			[]string{"k8s"},
		),
		concept(ConceptMongoDB, "mongodb", "mongodb",
			[]domain.ConceptID{ConceptDatabase},
			[]string{"mongo"},
			[]string{"mongo"},
		),
		concept(ConceptPostgreSQL, "postgresql", "postgresql",
			[]domain.ConceptID{ConceptDatabase},
			[]string{"postgres"},
			[]string{"postgres"},
		),
		concept(ConceptProfessionalExperience, "experiência profissional", "professional experience", nil,
			[]string{"experiencia profissional", "carreira", "trajetória profissional"},
			[]string{"career", "work experience", "employment history"},
		),
		concept(ConceptProduction, "produção", "production", nil,
			[]string{"producao", "ambiente produtivo", "sistemas em produção"},
			[]string{"production environment", "production systems"},
		),
		concept(ConceptAutomation, "automação", "automation", nil,
			[]string{"automacao", "automatização", "automatizar"},
			[]string{"automated", "automating"},
		),
		concept(ConceptSoftwareDesign, "design de software", "software design",
			[]domain.ConceptID{ConceptSoftwareDevelopment},
			[]string{"design patterns", "padrões de projeto"},
			[]string{"design patterns"},
		),
		concept(ConceptStrategyPattern, "strategy pattern", "strategy pattern",
			[]domain.ConceptID{ConceptSoftwareDesign},
			[]string{"padrão strategy", "padrao strategy"},
			[]string{"strategy design pattern"},
		),
		concept(ConceptArchitecture, "arquitetura", "architecture",
			[]domain.ConceptID{ConceptSoftwareDesign},
			[]string{"arquitetura de software", "arquitetura de sistemas"},
			[]string{"software architecture", "system architecture"},
		),
		concept(ConceptDataModeling, "modelagem de dados", "data modeling",
			[]domain.ConceptID{ConceptDatabase},
			[]string{"modelagem", "schemas", "schema"},
			[]string{"modelling", "schema design"},
		),
		concept(ConceptStorage, "armazenamento", "storage",
			[]domain.ConceptID{ConceptInfrastructure},
			[]string{"armazenar", "object storage"},
			[]string{"storing", "object storage"},
		),
		concept(ConceptSecurity, "segurança", "security", nil,
			[]string{"seguranca", "controle de acesso"},
			[]string{"secure", "access control"},
		),
		concept(ConceptDeployment, "deploy", "deployment",
			[]domain.ConceptID{ConceptDevOps},
			[]string{"implantação", "implantacao", "deploys"},
			[]string{"deploy", "deployments"},
		),
		concept(ConceptDNS, "dns", "dns",
			[]domain.ConceptID{ConceptInfrastructure},
			nil,
			nil,
		),
		concept(ConceptProxy, "proxy", "proxy",
			[]domain.ConceptID{ConceptInfrastructure},
			[]string{"proxy reverso"},
			[]string{"reverse proxy"},
		),
		concept(ConceptRouting, "roteamento", "routing",
			[]domain.ConceptID{ConceptInfrastructure},
			[]string{"rotas", "encaminhamento"},
			[]string{"routes"},
		),
		concept(ConceptMediaProcessing, "processamento de mídia", "media processing",
			[]domain.ConceptID{ConceptDataProcessing},
			[]string{"processamento de midia", "processamento de vídeo", "processamento de video"},
			[]string{"video processing", "media pipeline"},
		),
		concept(ConceptConcurrency, "concorrência", "concurrency", nil,
			[]string{"concorrencia", "concorrente", "paralelismo", "processamento paralelo", "tarefas simultâneas"},
			[]string{"concurrent", "parallelism", "parallel processing", "simultaneous tasks"},
		),
		concept(ConceptFaultIsolation, "isolamento de falhas", "fault isolation",
			[]domain.ConceptID{ConceptReliability},
			[]string{"isolar falhas", "isolamento"},
			[]string{"failure isolation", "isolating failures"},
		),
		concept(ConceptStreams, "streams", "streams",
			[]domain.ConceptID{ConceptDataProcessing},
			[]string{"stream", "fluxo de dados"},
			[]string{"stream", "data stream"},
		),
		concept(ConceptMemoryEfficiency, "eficiência de memória", "memory efficiency",
			[]domain.ConceptID{ConceptPerformance},
			[]string{"eficiencia de memoria", "uso de memória", "consumo de memória"},
			[]string{"memory usage", "memory consumption"},
		),
		concept(ConceptServerless, "serverless", "serverless",
			[]domain.ConceptID{ConceptCloud},
			[]string{"função serverless"},
			[]string{"serverless function"},
		),
		concept(ConceptStateless, "stateless", "stateless", nil,
			[]string{"sem estado"},
			[]string{"stateless architecture"},
		),
		concept(ConceptIntegration, "integração", "integration", nil,
			[]string{"integracao", "integrar", "integrações"},
			[]string{"integrations", "integrating"},
		),
		concept(ConceptDataMigration, "migração de dados", "data migration",
			[]domain.ConceptID{ConceptDataProcessing},
			[]string{"migracao de dados", "migrar dados"},
			[]string{"migrating data"},
		),
		concept(ConceptSearch, "busca", "search", nil,
			[]string{"pesquisa", "consulta", "consultas"},
			[]string{"query", "queries", "searching"},
		),
		concept(ConceptRetrieval, "recuperação de informação", "information retrieval",
			[]domain.ConceptID{ConceptSearch},
			[]string{"recuperacao", "retrieval", "recuperação de informação"},
			[]string{"retrieval"},
		),
		concept(ConceptSemanticSearch, "busca semântica", "semantic search",
			[]domain.ConceptID{ConceptSearch, ConceptRetrieval},
			[]string{"busca semantica", "recuperação semântica"},
			[]string{"semantic retrieval"},
		),
		concept(ConceptFullTextSearch, "busca textual", "full-text search",
			[]domain.ConceptID{ConceptSearch},
			[]string{"full text search", "pesquisa textual"},
			[]string{"text search", "full text search"},
		),
		concept(ConceptGeospatialSearch, "busca geoespacial", "geospatial search",
			[]domain.ConceptID{ConceptSearch},
			[]string{"busca por proximidade", "haversine", "geolocalização"},
			[]string{"proximity search", "haversine", "geolocation search"},
		),
		concept(ConceptAlgorithms, "algoritmos", "algorithms",
			[]domain.ConceptID{ConceptSoftwareDevelopment},
			[]string{"algoritmo"},
			[]string{"algorithm"},
		),
		concept(ConceptAuthentication, "autenticação", "authentication",
			[]domain.ConceptID{ConceptSecurity},
			[]string{"autenticacao", "login", "oauth", "jwt"},
			[]string{"auth", "login", "oauth", "jwt"},
		),
		concept(ConceptFileProcessing, "processamento de arquivos", "file processing",
			[]domain.ConceptID{ConceptDataProcessing},
			[]string{"processar arquivos"},
			[]string{"processing files"},
		),
		concept(ConceptCompression, "compressão", "compression",
			[]domain.ConceptID{ConceptFileProcessing},
			[]string{"compressao", "compactação", "arquivamento"},
			[]string{"compressing", "archiving"},
		),
		concept(ConceptStreaming, "streaming", "streaming",
			[]domain.ConceptID{ConceptMediaProcessing},
			[]string{"vídeo sob demanda", "video sob demanda"},
			[]string{"video streaming", "media streaming"},
		),
		concept(ConceptLeadership, "liderança", "leadership", nil,
			[]string{"lideranca", "liderança técnica", "liderar"},
			[]string{"technical leadership", "leading", "led"},
		),
		concept(ConceptTeamwork, "trabalho em equipe", "teamwork", nil,
			[]string{"equipe", "time", "colaboração"},
			[]string{"team", "collaboration"},
		),
		concept(ConceptEventDriven, "arquitetura orientada a eventos", "event-driven architecture", nil,
			[]string{"event driven", "orientado a eventos", "eventos"},
			[]string{"event driven", "events", "event-based architecture"},
		),
		concept(ConceptDistributedSystems, "sistemas distribuídos", "distributed systems", nil,
			[]string{"sistemas distribuidos", "execução distribuída", "execucao distribuida", "distribuído"},
			[]string{"distributed system", "distributed execution", "distributed"},
		),
		concept(ConceptScalability, "escalabilidade", "scalability", nil,
			[]string{"escalar", "escala horizontal"},
			[]string{"scalable", "horizontal scaling"},
		),
		concept(ConceptObservability, "observabilidade", "observability", nil,
			[]string{"monitoramento", "métricas", "metricas"},
			[]string{"monitoring", "metrics"},
		),
		concept(ConceptDataIntegrity, "integridade de dados", "data integrity",
			[]domain.ConceptID{ConceptReliability},
			[]string{"integridade", "integridade determinística"},
			[]string{"integrity", "deterministic integrity"},
		),
		concept(ConceptFileFormat, "formato de arquivo", "file format",
			[]domain.ConceptID{ConceptFileProcessing},
			[]string{"formato versionado", "manifesto"},
			[]string{"versioned format", "manifest"},
		),
		concept(ConceptChunking, "chunking", "chunking",
			[]domain.ConceptID{ConceptFileProcessing},
			[]string{"chunk", "chunks", "indexação por chunks"},
			[]string{"chunk", "chunks", "chunk indexing"},
		),
		concept(ConceptGoroutines, "goroutines", "goroutines",
			[]domain.ConceptID{ConceptConcurrency},
			[]string{"goroutine"},
			[]string{"goroutine"},
		),
		concept(ConceptOrderedProcessing, "processamento ordenado", "ordered processing",
			[]domain.ConceptID{ConceptDataProcessing},
			[]string{"escrita ordenada", "ordenação"},
			[]string{"ordered writes", "ordered execution"},
		),
		concept(ConceptBenchmark, "benchmark", "benchmark",
			[]domain.ConceptID{ConceptPerformance},
			[]string{"benchmarks", "teste de desempenho"},
			[]string{"benchmarks", "performance test"},
		),
		concept(ConceptThroughput, "throughput", "throughput",
			[]domain.ConceptID{ConceptPerformance},
			[]string{"taxa de processamento", "vazão"},
			[]string{"processing rate"},
		),
		concept(ConceptChecksum, "checksum", "checksum",
			[]domain.ConceptID{ConceptDataIntegrity},
			[]string{"soma de verificação"},
			[]string{"hash verification"},
		),
		concept(ConceptAtomicity, "atomicidade", "atomicity",
			[]domain.ConceptID{ConceptConsistency},
			[]string{"operações atômicas", "atômico"},
			[]string{"atomic operations", "atomic"},
		),
		concept(ConceptSafeExtraction, "extração segura", "safe extraction",
			[]domain.ConceptID{ConceptReliability},
			[]string{"extracao segura", "isolamento temporário"},
			[]string{"safe unpacking", "temporary isolation"},
		),
		concept(ConceptElectoralSystem, "sistema eleitoral", "electoral system", nil,
			[]string{"plataforma eleitoral", "eleição", "votação"},
			[]string{"electoral platform", "election", "voting"},
		),
		concept(ConceptCrossPlatform, "multiplataforma", "cross-platform",
			[]domain.ConceptID{ConceptSoftwareDevelopment},
			[]string{"cross platform", "desktop e mobile"},
			[]string{"cross platform", "desktop and mobile"},
		),
		concept(ConceptResourceEfficiency, "eficiência de recursos", "resource efficiency",
			[]domain.ConceptID{ConceptPerformance},
			[]string{"eficiencia de recursos", "baixo consumo de recursos"},
			[]string{"low resource usage", "resource consumption"},
		),
		concept(ConceptSecurePersistence, "persistência segura", "secure persistence",
			[]domain.ConceptID{ConceptSecurity, ConceptDataIntegrity},
			[]string{"persistencia segura", "persistência dos votos"},
			[]string{"secure data persistence", "secure vote persistence"},
		),
		concept(ConceptUsage, "uso", "usage", nil,
			[]string{"utilização", "usuarios", "usuários"},
			[]string{"users", "adoption"},
		),
		concept(ConceptRealWorldUse, "uso real", "real-world use",
			[]domain.ConceptID{ConceptUsage},
			[]string{"uso em produção", "utilizado de verdade"},
			[]string{"real world usage", "production use"},
		),
		concept(ConceptEducation, "educação", "education", nil,
			[]string{"educacao", "formação", "formacao", "estudos", "curso"},
			[]string{"studies", "academic background", "course"},
		),
		concept(ConceptLanguage, "idioma", "language", nil,
			[]string{"idiomas", "língua", "português", "portugues", "inglês", "ingles"},
			[]string{"languages", "spoken language", "portuguese", "english"},
		),
		concept(ConceptFluency, "fluência", "fluency", nil,
			[]string{"fluencia", "nível de idioma"},
			[]string{"language proficiency", "proficiency"},
		),
	}
}

func concept(
	id domain.ConceptID,
	pt string,
	en string,
	parents []domain.ConceptID,
	ptAliases []string,
	enAliases []string,
) domain.Concept {
	return domain.Concept{
		ID: id,
		Name: domain.LocalizedText{
			PT: pt,
			EN: en,
		},
		Aliases: map[domain.Language][]string{
			domain.LanguagePortuguese: ptAliases,
			domain.LanguageEnglish:    enAliases,
		},
		ParentIDs: parents,
	}
}
